### ISSUE TITLE
bug: Difference in function Id

### ISSUE THREAD

**Issue by greged93** [lambdaclass/cairo_native#453]
Getting the below error running a test on the Kakarot test suite with native (using commit 5b8bfd601a81b3eb6520d7c576d6002ce9decfbf from Native):
```
Difference in FunctionId { id: 4, debug_name: Some("contracts::eoa::ExternallyOwnedAccount::__wrapper__AccountContractImpl____validate__") }: Some(OrderedHashMap({Bitwise: 16})) != Some(OrderedHashMap({})).
Difference in FunctionId { id: 4, debug_name: Some("contracts::eoa::ExternallyOwnedAccount::__wrapper__AccountContractImpl____validate__") }: Some(OrderedHashMap({Bitwise: 16})) != Some(OrderedHashMap({})).
thread 'evm_sequencer::evm_state::v1::tests::test_execute_simple_contract' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-sierra-gas-2.5.4/src/gas_info.rs:97:9:
Comparison failed.
```

The EOA contract used can be found here: https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/contracts/src/eoa.cairo
and was compiled using scarb 2.5.4.

**Comment by greged93** [comment]
```
libunwind: malformed __unwind_info at 0x18442ECA8 bad second level page
test evm_sequencer::evm_state::v1::tests::test_execute_simple_contract ... FAILED

failures:

---- evm_sequencer::evm_state::v1::tests::test_execute_simple_contract stdout ----
Difference in FunctionId { id: 4, debug_name: Some("contracts::eoa::ExternallyOwnedAccount::__wrapper__AccountContractImpl____validate__") }: Some(OrderedHashMap({Bitwise: 16})) != Some(OrderedHashMap({})).
Difference in FunctionId { id: 4, debug_name: Some("contracts::eoa::ExternallyOwnedAccount::__wrapper__AccountContractImpl____validate__") }: Some(OrderedHashMap({Bitwise: 16})) != Some(OrderedHashMap({})).
thread 'evm_sequencer::evm_state::v1::tests::test_execute_simple_contract' panicked at /Users/greg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-sierra-gas-2.5.4/src/gas_info.rs:97:9:
Comparison failed.
stack backtrace:
   0:        0x1093b40e8 - std::backtrace_rs::backtrace::libunwind::trace::h2bec7eee3e3e24f0
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1093b40e8 - std::backtrace_rs::backtrace::trace_unsynchronized::h10108c5a95780dd0
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1093b40e8 - std::sys_common::backtrace::_print_fmt::h5f5c96cd31c48b74
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1093b40e8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha4143958c069f4f2
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1093d2d2c - core::fmt::rt::Argument::fmt::h38a811886c530c84
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/fmt/rt.rs:138:9
   5:        0x1093d2d2c - core::fmt::write::he47bc624e50aa64f
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/fmt/mod.rs:1114:21
   6:        0x1093b198c - std::io::Write::write_fmt::hbca19b51bebf03d8
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/io/mod.rs:1714:15
   7:        0x1093b3f28 - std::sys_common::backtrace::_print::hc6d1ce10148efaf3
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1093b3f28 - std::sys_common::backtrace::print::h76d3743d51c2c93d
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1093b5ad0 - std::panicking::default_hook::{{closure}}::h1e5e245fb0a51028
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:272:22
  10:        0x1093b5710 - std::panicking::default_hook::h67c3e1da2def7505
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:289:9
  11:        0x100ac923c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd5dc1550272dfdf8
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/alloc/src/boxed.rs:2021:9
  12:        0x100ac923c - test::test_main::{{closure}}::h86eb90c8f4e36dee
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:136:21
  13:        0x1093b6150 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h89b1498bc5995536
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/alloc/src/boxed.rs:2021:9
  14:        0x1093b6150 - std::panicking::rust_panic_with_hook::hc0a5a4fb3727e423
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:735:13
  15:        0x1093b5edc - std::panicking::begin_panic_handler::{{closure}}::hb43691ae6b22a6a2
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:601:13
  16:        0x1093b4574 - std::sys_common::backtrace::__rust_end_short_backtrace::h743ce805e9eda2a0
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:170:18
  17:        0x1093b5c88 - rust_begin_unwind
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:597:5
  18:        0x109d820ac - core::panicking::panic_fmt::h880bc26b9b9f9f7a
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/panicking.rs:72:14
  19:        0x1090f3f40 - cairo_lang_sierra_gas::gas_info::GasInfo::assert_eq_functions::h25befb624ff1eda5
                               at /Users/greg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-sierra-gas-2.5.4/src/gas_info.rs:97:9
  20:        0x100d157f0 - cairo_native::metadata::gas::calc_metadata::h8af16c53c4511785
                               at /Users/greg/.cargo/git/checkouts/cairo_native-0bad8506281b7281/33978ac/src/metadata/gas.rs:169:5
  21:        0x100d14ec0 - cairo_native::metadata::gas::GasMetadata::new::h509f886e99358a7f
                               at /Users/greg/.cargo/git/checkouts/cairo_native-0bad8506281b7281/33978ac/src/metadata/gas.rs:62:13
  22:        0x100d25c98 - cairo_native::context::NativeContext::compile::h5a089288e1e480c9
                               at /Users/greg/.cargo/git/checkouts/cairo_native-0bad8506281b7281/33978ac/src/context.rs:59:13
  23:        0x100985b84 - cairo_native::cache::jit::JitProgramCache<K>::compile_and_insert::h2895da3442a10247
                               at /Users/greg/.cargo/git/checkouts/cairo_native-0bad8506281b7281/33978ac/src/cache/jit.rs:48:22
  24:        0x100a18708 - starknet_in_rust::execution::execution_entry_point::ExecutionEntryPoint::native_execute::hbd2be528d9c52c27
                               at /Users/greg/code/rust/starknet_in_rust/src/execution/execution_entry_point.rs:733:25
  25:        0x100a18708 - starknet_in_rust::execution::execution_entry_point::ExecutionEntryPoint::execute::hb0d7a4ad8a8a79a7
                               at /Users/greg/code/rust/starknet_in_rust/src/execution/execution_entry_point.rs:168:23
  26:        0x100a427d0 - starknet_in_rust::transaction::invoke_function::InvokeFunction::run_execute_entrypoint::hb5619f5b6f8a84a9
                               at /Users/greg/code/rust/starknet_in_rust/src/transaction/invoke_function.rs:335:9
  27:        0x100a43624 - starknet_in_rust::transaction::invoke_function::InvokeFunction::apply::h399c1c86364b5e36
                               at /Users/greg/code/rust/starknet_in_rust/src/transaction/invoke_function.rs:388:13
  28:        0x100a46754 - starknet_in_rust::transaction::invoke_function::InvokeFunction::execute::{{closure}}::h31fcbd25a60d2bbd
                               at /Users/greg/code/rust/starknet_in_rust/src/transaction/invoke_function.rs:461:28
  29:        0x100a440b0 - starknet_in_rust::transaction::invoke_function::InvokeFunction::execute::hf91bf2257fb07acf
                               at /Users/greg/code/rust/starknet_in_rust/src/transaction/invoke_function.rs:425:5
  30:        0x100a41e50 - starknet_in_rust::transaction::Transaction::execute::h21d41d44e0dc9e20
                               at /Users/greg/code/rust/starknet_in_rust/src/transaction/mod.rs:224:48
  31:        0x1009f7594 - <sequencer::sequencer::Sequencer<S> as sequencer::execution::Execution>::execute::h6dab1473d95af4c1
                               at /Users/greg/code/rust/ef-tests/crates/sequencer/src/sequencer.rs:73:19
  32:        0x10095a6b0 - ef_testing::evm_sequencer::evm_state::v1::<impl ef_testing::evm_sequencer::evm_state::Evm for ef_testing::evm_sequencer::sequencer::KakarotSequencer>::execute_transaction::hf258c05bac8ec9a3
                               at /Users/greg/code/rust/ef-tests/crates/ef-testing/src/evm_sequencer/evm_state/v1.rs:260:9
  33:        0x100987b88 - ef_testing::evm_sequencer::evm_state::v1::tests::test_execute_simple_contract::h6af10779f74fa4ad
                               at /Users/greg/code/rust/ef-tests/crates/ef-testing/src/evm_sequencer/evm_state/v1.rs:357:9
  34:        0x1009f2278 - ef_testing::evm_sequencer::evm_state::v1::tests::test_execute_simple_contract::{{closure}}::ha8e682186eb34e7e
                               at /Users/greg/code/rust/ef-tests/crates/ef-testing/src/evm_sequencer/evm_state/v1.rs:322:39
  35:        0x10099aa9c - core::ops::function::FnOnce::call_once::hf756fbf4fb8c57ca
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/ops/function.rs:250:5
  36:        0x100acd1c8 - core::ops::function::FnOnce::call_once::hbd1281834e7abef7
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/ops/function.rs:250:5
  37:        0x100acd1c8 - test::__rust_begin_short_backtrace::he31ca7446c72dc96
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:626:18
  38:        0x100acc160 - test::run_test_in_process::{{closure}}::hea8d7fbe13d64714
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:649:60
  39:        0x100acc160 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h00f39b186b7de152
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/panic/unwind_safe.rs:271:9
  40:        0x100acc160 - std::panicking::try::do_call::h6e0c061be40b43de
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:504:40
  41:        0x100acc160 - std::panicking::try::h1c3ffd3a316678f9
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:468:19
  42:        0x100acc160 - std::panic::catch_unwind::h942dd2e8d0646225
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panic.rs:142:14
  43:        0x100acc160 - test::run_test_in_process::hd7b54819b5936569
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:649:27
  44:        0x100acc160 - test::run_test::{{closure}}::h7ce85d57e5d482e1
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:572:43
  45:        0x100a9fa68 - test::run_test::{{closure}}::hecce2bbca69bbe49
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/test/src/lib.rs:600:41
  46:        0x100a9fa68 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5e5ab835372bcd6
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys_common/backtrace.rs:154:18
  47:        0x100aa40b0 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h0ad6e88834e1d414
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/thread/mod.rs:529:17
  48:        0x100aa40b0 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf86fd99e435ae9a0
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/panic/unwind_safe.rs:271:9
  49:        0x100aa40b0 - std::panicking::try::do_call::h60bf889da1413290
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:504:40
  50:        0x100aa40b0 - std::panicking::try::ha4f16eebfc84d55e
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panicking.rs:468:19
  51:        0x100aa40b0 - std::panic::catch_unwind::h5aa0012890669879
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/panic.rs:142:14
  52:        0x100aa40b0 - std::thread::Builder::spawn_unchecked_::{{closure}}::hae996083b5b068a9
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/thread/mod.rs:528:30
  53:        0x100aa40b0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ebd6a6dd4e39434
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/core/src/ops/function.rs:250:5
  54:        0x1093b9c60 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha4f599b8d12c44ad
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/alloc/src/boxed.rs:2007:9
  55:        0x1093b9c60 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4c4649bce5ad6ecd
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/alloc/src/boxed.rs:2007:9
  56:        0x1093b9c60 - std::sys::unix::thread::Thread::new::thread_start::h97e7f16b037c0653
                               at /rustc/b3aa8e7168a3d940122db3561289ffbf3f587262/library/std/src/sys/unix/thread.rs:108:17
  57:        0x184429034 - __pthread_joiner_wake
  ```

**Comment by edg-l** [comment]
Can you try with the following versions?

native: 1844307d38633d9774cc14fcd3cd183b1989d2e5
starknet_in_rust: 5e44291002d555bb8e88b7c4b04de1c36632723e

note, this updates both to use cairo 2.5.4

**Comment by greged93** [comment]
@edg-l This fixes the gas issue but getting another issue now, will open
