### ISSUE TITLE
Error when compiling Kakarot core contract

### ISSUE THREAD

**Issue by greged93** [lambdaclass/cairo_native#628]
We are getting an error when compiling the `function_call` libfunc. Below is the call trace for it:
```rust
thread 'tests::starknet::kakarot::compile_to_native::_tests_tests_starknet_contracts_kakarot_contracts_kakarotcore_contract_class_json_expects' panicked at src/libfuncs/function_call.rs:193:52:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:209:5
   3: index<(&cairo_lang_sierra::ids::ConcreteTypeId, &cairo_lang_sierra::extensions::core::CoreTypeConcrete)>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/index.rs:264:10
   4: index<(&cairo_lang_sierra::ids::ConcreteTypeId, &cairo_lang_sierra::extensions::core::CoreTypeConcrete), usize>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/index.rs:18:9
   5: index<(&cairo_lang_sierra::ids::ConcreteTypeId, &cairo_lang_sierra::extensions::core::CoreTypeConcrete), usize, alloc::alloc::Global>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/mod.rs:2829:9
   6: build
   7: {closure#5}
             at ./src/compiler.rs:407:21
   8: foreach_statement_in_function<(std::collections::hash::map::HashMap<cairo_lang_sierra::ids::VarId, melior::ir::value::Value, std::hash::random::RandomState>, alloc::collections::btree::map::BTreeMap<usize, usize, alloc::alloc::Global>), cairo_native::error::Error, cairo_native::compiler::compile_func::{closure_env#5}>
             at ./src/compiler.rs:905:29
   9: compile_func
             at ./src/compiler.rs:284:5
  10: compile
             at ./src/compiler.rs:121:9
  11: compile
             at ./src/context.rs:123:9
  12: compile_to_native
             at ./tests/tests/starknet/kakarot.rs:24:5
  13: _tests_tests_starknet_contracts_kakarot_contracts_kakarotcore_contract_class_json_expects
             at ./tests/tests/starknet/kakarot.rs:5:1
  14: {closure#0}
             at ./tests/tests/starknet/kakarot.rs:5:101
  15: call_once<entry::tests::starknet::kakarot::compile_to_native::_tests_tests_starknet_contracts_kakarot_contracts_kakarotcore_contract_class_json_expects::{closure_env#0}, ()>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
libunwind: malformed __unwind_info at 0x182BF8CA8 bad second level page
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::starknet::kakarot::compile_to_native::_tests_tests_starknet_contracts_kakarot_contracts_kakarotcore_contract_class_json_expects ... FAILED
```

Also linking a PR adding a test for reproduction.

**Comment by edg-l** [comment]
Is this fixed with your pr?

**Comment by greged93** [comment]
I quickly need to check but the reason it was failing compilation was because of the `no_op` function so hopefully yes

**Comment by greged93** [comment]
can confirm this can be closed!
