### ISSUE TITLE
Downcast panic in tx 0x7dc9fa07e754386498c5fe7b942da1d3a0a8f1de53c98b14aafc8aa411fe658

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#821]
There is a downcast panic executing tx 0x7dc9fa07e754386498c5fe7b942da1d3a0a8f1de53c98b14aafc8aa411fe658 in block 742679

In starknet-replay branch `with-state-dump`
```
cargo run --release tx 0x7dc9fa07e754386498c5fe7b942da1d3a0a8f1de53c98b14aafc8aa411fe658 mainnet 742679
```

```
thread 'main' panicked at /Users/peter/.cargo/git/checkouts/cairo_native-6d7d3936f1e5c86c/6fb1fec/src/libfuncs/cast.rs:92:5:
invalid downcast `[68]` into `[37]`: target range contains the source range
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10a364798 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x10a384a50 - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x10a360c50 - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x10a365874 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x10a365498 - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x10a366338 - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   6:        0x10a365c60 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   7:        0x10a364c24 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   8:        0x10a365950 - _rust_begin_unwind
   9:        0x10a73421c - core::panicking::panic_nounwind_fmt::h91ee161184879b56
  10:        0x10a734294 - core::panicking::panic_nounwind::heab7ebe7a6cd845c
  11:        0x10a734338 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
  12:        0x100e05004 - cairo_native::starknet::handler::StarknetSyscallHandlerCallbacks<T>::wrap_call_contract::hb3e2d668dd2bfca4
  13:        0x113b7b4f4 - _impl$f16
  14:        0x113b6bff8 - _impl$f0
  15:        0x113b6c26c - __mlir_ciface_f0
thread caused non-unwinding panic. aborting.
[1]    55841 abort      cargo run --release tx  mainnet 742679
```

**Comment by edg-l** [comment]
This comes from a assert int he cast libfuncs when compiling

**Comment by edg-l** [comment]
Adding the ranges to the print:

```
invalid downcast `[68]` (Range { lower: 0, upper: 256 }) into `[37]` (Range { lower: 0, upper: 4294967296 }): target range contains the source range
```
